### ISSUE TITLE
Both "invalid credentials" and "enter OTP you received" message appear if there is space in email field on login page

### ISSUE THREAD

**Issue by mayur7194** [CSE545/BankingSystem#55]
If there is a space in the email field on the login page, it gives both "invalid credentials" and "enter OTP you received" message.  

![bug](https://user-images.githubusercontent.com/42981058/78246507-21dce180-749e-11ea-954e-1d5e57f83165.PNG)

**Comment by ripu23** [comment]
PR link: https://github.com/CSE545/BankingSystem/pull/60
Fixed
